/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:24:40
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 8
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 17
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.6644189045547,                 0,                 0 
  },
  {
                   1,   -1.997437344632,                 1 
  },
  {
     0.6644189045547,                 0,                 0 
  },
  {
                   1,   -1.991861144822,                 1 
  },
  {
     0.5994926955551,                 0,                 0 
  },
  {
                   1,   -1.997681844642,                 1 
  },
  {
     0.5994926955551,                 0,                 0 
  },
  {
                   1,   -1.991004106634,                 1 
  },
  {
     0.4459708590235,                 0,                 0 
  },
  {
                   1,   -1.998308457351,                 1 
  },
  {
     0.4459708590235,                 0,                 0 
  },
  {
                   1,   -1.987680017811,                 1 
  },
  {
     0.1726450544505,                 0,                 0 
  },
  {
                   1,   -1.999568727959,                 1 
  },
  {
     0.1726450544505,                 0,                 0 
  },
  {
                   1,   -1.952094474091,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.988756504647,   0.9954444499664 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.99378491268,   0.9968922725602 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.978734056014,   0.9853180901622 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.986732696099,    0.989862052686 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.967110259125,   0.9732915885234 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.977152490652,   0.9804500090907 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.959571416474,   0.9647216393635 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.965269837906,   0.9691883101202 
  },
  {
                   1,                 0,                 0 
  }
};
