/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:26:45
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 8
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 17
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.6628887439087,                 0,                 0 
  },
  {
                   1,   -1.983756584806,                 1 
  },
  {
     0.6628887439087,                 0,                 0 
  },
  {
                   1,   -1.948615005715,                 1 
  },
  {
     0.5945211178826,                 0,                 0 
  },
  {
                   1,   -1.985305714042,                 1 
  },
  {
     0.5945211178826,                 0,                 0 
  },
  {
                   1,   -1.943252876068,                 1 
  },
  {
     0.4395836026516,                 0,                 0 
  },
  {
                   1,   -1.989277571992,                 1 
  },
  {
     0.4395836026516,                 0,                 0 
  },
  {
                   1,   -1.922563245444,                 1 
  },
  {
     0.1727710479932,                 0,                 0 
  },
  {
                   1,   -1.997267895768,                 1 
  },
  {
     0.1727710479932,                 0,                 0 
  },
  {
                   1,   -1.711841468163,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.946465299235,   0.9886018249589 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.972541312845,   0.9921877138099 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,     -1.9223691173,   0.9635400067973 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.954970568155,   0.9746507525547 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.895915857618,   0.9342367506454 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.930878073656,   0.9514678084862 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.881836352735,   0.9135878295003 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.899934058851,   0.9241892302859 
  },
  {
                   1,                 0,                 0 
  }
};
