/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:33:02
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 8
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 17
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.6603921097098,                 0,                 0 
  },
  {
                   1,    -1.74540448258,                 1 
  },
  {
     0.6603921097098,                 0,                 0 
  },
  {
                   1,   -1.239604786949,                 1 
  },
  {
     0.5788474144388,                 0,                 0 
  },
  {
                   1,   -1.769737891547,                 1 
  },
  {
     0.5788474144388,                 0,                 0 
  },
  {
                   1,   -1.171560122758,                 1 
  },
  {
     0.4257614365753,                 0,                 0 
  },
  {
                   1,   -1.832447312503,                 1 
  },
  {
     0.4257614365753,                 0,                 0 
  },
  {
                   1,  -0.9305268806161,                 1 
  },
  {
      0.211128097478,                 0,                 0 
  },
  {
                   1,   -1.958106573411,                 1 
  },
  {
      0.211128097478,                 0,                 0 
  },
  {
                   1,    0.404749532981,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.330260819216,   0.9571198086945 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.664609308268,   0.9686073600869 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.274747109197,   0.8672616466359 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.604260404145,    0.900815340301 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.235079769952,   0.7680707179068 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.517050360807,   0.8167575827891 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.387519748686,   0.7264804873216 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.263924860321,   0.6980910497168 
  },
  {
                   1,                 0,                 0 
  }
};
