/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:32:08
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 8
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 17
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
      0.660581842794,                 0,                 0 
  },
  {
                   1,   -1.897602346475,                 1 
  },
  {
      0.660581842794,                 0,                 0 
  },
  {
                   1,   -1.682567685062,                 1 
  },
  {
     0.5847533833589,                 0,                 0 
  },
  {
                   1,   -1.907378270269,                 1 
  },
  {
     0.5847533833589,                 0,                 0 
  },
  {
                   1,    -1.65118197151,                 1 
  },
  {
       0.42915663623,                 0,                 0 
  },
  {
                   1,   -1.932486375785,                 1 
  },
  {
       0.42915663623,                 0,                 0 
  },
  {
                   1,   -1.533858437228,                 1 
  },
  {
     0.1866246911329,                 0,                 0 
  },
  {
                   1,   -1.982917104704,                 1 
  },
  {
     0.1866246911329,                 0,                 0 
  },
  {
                   1,   -0.617803669028,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.711841059168,   0.9719534203342 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.857231044379,   0.9803089774419 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.662206266199,   0.9118613488531 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.815310709608,   0.9369599451733 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.615969936482,   0.8439205024765 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.756419807224,   0.8814639532737 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.67474103602,   0.8189854400554 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.60973958248,   0.7965788004251 
  },
  {
                   1,                 0,                 0 
  }
};
