/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:46:05
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 19
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
      0.722594844051,                 0,                 0 
  },
  {
                   1,    1.916794230436,                 1 
  },
  {
      0.722594844051,                 0,                 0 
  },
  {
                   1,   0.9944565080092,                 1 
  },
  {
     0.6445722669205,                 0,                 0 
  },
  {
                   1,    1.928881749314,                 1 
  },
  {
     0.6445722669205,                 0,                 0 
  },
  {
                   1,   0.8692589251746,                 1 
  },
  {
     0.5277410573334,                 0,                 0 
  },
  {
                   1,    1.952892151876,                 1 
  },
  {
     0.5277410573334,                 0,                 0 
  },
  {
                   1,   0.5022098637592,                 1 
  },
  {
     0.3810482792859,                 0,                 0 
  },
  {
                   1,    1.983521776079,                 1 
  },
  {
     0.3810482792859,                 0,                 0 
  },
  {
                   1,  -0.5318388471979,                 1 
  },
  {
     0.2933993691209,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.185567578947,   0.9141849574145 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,     1.84652787502,   0.9621133048763 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.074129273904,   0.7445732957591 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.772763405305,    0.882385302652 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.677328532828,   0.7829109887453 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.9692117023525,   0.5606629305122 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.521689464366,   0.6388984603774 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.9430786145738,   0.3923119645476 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.193074365444,   0.4132012617583 
  },
  {
                   1,                 0,                 0 
  }
};
