/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:22:08
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 8
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 17
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.6651272326522,                 0,                 0 
  },
  {
                   1,    -1.99959394719,                 1 
  },
  {
     0.6651272326522,                 0,                 0 
  },
  {
                   1,   -1.998717700299,                 1 
  },
  {
     0.6016530165126,                 0,                 0 
  },
  {
                   1,   -1.999632503388,                 1 
  },
  {
     0.6016530165126,                 0,                 0 
  },
  {
                   1,   -1.998583200812,                 1 
  },
  {
     0.4489022216885,                 0,                 0 
  },
  {
                   1,   -1.999731440886,                 1 
  },
  {
     0.4489022216885,                 0,                 0 
  },
  {
                   1,   -1.998061455317,                 1 
  },
  {
     0.1736650071881,                 0,                 0 
  },
  {
                   1,   -1.999931238455,                 1 
  },
  {
     0.1736650071881,                 0,                 0 
  },
  {
                   1,   -1.992438976303,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.997141883113,   0.9981978995123 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.998276931596,   0.9987692631115 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.993131380898,    0.994174220925 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.995479818295,    0.995976672126 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.988380189712,   0.9893630546768 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.991695598448,   0.9922205128492 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.985088629035,   0.9859103911747 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.987078115631,   0.9877034356442 
  },
  {
                   1,                 0,                 0 
  }
};
