/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:35:46
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 19
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.7178132974895,                 0,                 0 
  },
  {
                   1,   -1.378138974972,                 1 
  },
  {
     0.7178132974895,                 0,                 0 
  },
  {
                   1,  -0.3124046519866,                 1 
  },
  {
      0.644063742127,                 0,                 0 
  },
  {
                   1,   -1.424047780796,                 1 
  },
  {
      0.644063742127,                 0,                 0 
  },
  {
                   1,  -0.2238510869153,                 1 
  },
  {
     0.5232268356316,                 0,                 0 
  },
  {
                   1,   -1.537140013447,                 1 
  },
  {
     0.5232268356316,                 0,                 0 
  },
  {
                   1,  0.02630073838818,                 1 
  },
  {
     0.3567493812584,                 0,                 0 
  },
  {
                   1,   -1.766832737908,                 1 
  },
  {
     0.3567493812584,                 0,                 0 
  },
  {
                   1,   0.7383082555723,                 1 
  },
  {
     0.2441771058138,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.4820497765721,   0.9443345134023 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.242508610073,   0.9553802041993 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.4531525190072,   0.8291221623107 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.183019968005,   0.8614218615167 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.095964198297,   0.7467117326194 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.4413437310755,   0.6951941518756 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.9405548285043,   0.6094817248198 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -0.502923583825,   0.5588269495528 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.7007391594351,   0.5116457883724 
  },
  {
                   1,                 0,                 0 
  }
};
