/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:42:38
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 8
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 17
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.7969506487386,                 0,                 0 
  },
  {
                   1,    1.868224202711,                 1 
  },
  {
     0.7624852910766,                 0,                 0 
  },
  {
                   1,    1.857862572747,                 1 
  },
  {
     0.7118035777928,                 0,                 0 
  },
  {
                   1,    1.833700856471,                 1 
  },
  {
     0.6380580478356,                 0,                 0 
  },
  {
                   1,    1.786220252672,                 1 
  },
  {
     0.5323301376076,                 0,                 0 
  },
  {
                   1,    1.690605959515,                 1 
  },
  {
     0.3884594228814,                 0,                 0 
  },
  {
                   1,    1.472733971585,                 1 
  },
  {
     0.2207602866871,                 0,                 0 
  },
  {
                   1,   0.8563472118882,                 1 
  },
  {
    0.09285729066807,                 0,                 0 
  },
  {
                   1,   -1.113432048381,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,     1.86734599555,   0.9723648026875 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.807161054541,   0.9155387521332 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.731821328332,   0.8501936536795 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.631280290105,   0.7676841783519 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.493500410563,   0.6582001827094 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.310226574376,   0.5150480314787 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.098902210371,   0.3513753277449 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.9384768207046,   0.2275816853964 
  },
  {
                   1,                 0,                 0 
  }
};
