/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:23:28
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 8
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 17
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.6648463805662,                 0,                 0 
  },
  {
                   1,   -1.998983482217,                 1 
  },
  {
     0.6648463805662,                 0,                 0 
  },
  {
                   1,   -1.996772362475,                 1 
  },
  {
     0.6008046038214,                 0,                 0 
  },
  {
                   1,     -1.9990804206,                 1 
  },
  {
     0.6008046038214,                 0,                 0 
  },
  {
                   1,   -1.996432334893,                 1 
  },
  {
     0.4477408672867,                 0,                 0 
  },
  {
                   1,   -1.999328881269,                 1 
  },
  {
     0.4477408672867,                 0,                 0 
  },
  {
                   1,   -1.995112829156,                 1 
  },
  {
     0.1731939879994,                 0,                 0 
  },
  {
                   1,   -1.999828804627,                 1 
  },
  {
     0.1731939879994,                 0,                 0 
  },
  {
                   1,   -1.980907089593,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.994475653228,   0.9971300322532 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.996809846019,   0.9980430252371 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.98811512411,   0.9907331688561 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.992364149107,   0.9936076762033 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.980641893649,   0.9831052929169 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.986338914369,   0.9876515333211 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.975594790273,    0.977650583029 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.978934546823,   0.9804975074847 
  },
  {
                   1,                 0,                 0 
  }
};
