/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:31:00
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 8
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 17
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.6617301742155,                 0,                 0 
  },
  {
                   1,   -1.959192838272,                 1 
  },
  {
     0.6617301742155,                 0,                 0 
  },
  {
                   1,   -1.871371805233,                 1 
  },
  {
     0.5902614265018,                 0,                 0 
  },
  {
                   1,   -1.963092359709,                 1 
  },
  {
     0.5902614265018,                 0,                 0 
  },
  {
                   1,   -1.858128352557,                 1 
  },
  {
     0.4346061708403,                 0,                 0 
  },
  {
                   1,   -1.973090686094,                 1 
  },
  {
     0.4346061708403,                 0,                 0 
  },
  {
                   1,   -1.807484786398,                 1 
  },
  {
     0.1761760110668,                 0,                 0 
  },
  {
                   1,    -1.99316686837,                 1 
  },
  {
     0.1761760110668,                 0,                 0 
  },
  {
                   1,    -1.33298953466,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.876680848551,   0.9820032581567 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.938329772047,   0.9875859187885 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.84066773638,    0.942841312672 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.910842293951,   0.9599279502078 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.803353919628,    0.897695191088 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.872805175918,   0.9238111278254 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.788360113627,   0.8661295515105 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.82238513559,   0.8819972622867 
  },
  {
                   1,                 0,                 0 
  }
};
