/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
 * Generated on: 17-Jun-2018 18:45:36
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 6
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft\Matlab2018a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 13
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.5113197755006,                 0,                 0 
  },
  {
                   1,    1.812885794829,                 1 
  },
  {
     0.5113197755006,                 0,                 0 
  },
  {
                   1,   0.8995612535092,                 1 
  },
  {
     0.3885385684591,                 0,                 0 
  },
  {
                   1,    1.863742987538,                 1 
  },
  {
     0.3885385684591,                 0,                 0 
  },
  {
                   1,   0.6175886019267,                 1 
  },
  {
     0.2142861286824,                 0,                 0 
  },
  {
                   1,    1.969615220936,                 1 
  },
  {
     0.2142861286824,                 0,                 0 
  },
  {
                   1,  -0.8349082428665,                 1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.195758458076,   0.9126459001351 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.650327526063,   0.9402903152186 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.138876420806,   0.7550350628555 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.525978724229,   0.8185370746048 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.354687386976,   0.6972849531171 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    1.185552806809,   0.6572061330757 
  },
  {
                   1,                 0,                 0 
  }
};
